### ISSUE TITLE
Remove ability to download collection 1 

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/coastsat_package#12]
## Tasks

- [x] update `retrieve_images` to no longer reference collection 1 `C01`

- [x] update `check_images_available` to no longer reference collection 1 `C01`

- [x] update `check_images_available` to no longer reference collection 1 `C01`

- [x] if C01 is requested switch to C02 and tell the user that C01 has been deprecated

## Example Error Message

```
Attention required for LANDSAT/LT05/C01/T1_TOA! You are using a deprecated asset.
To ensure continued functionality, please update it by July 1, 2024.
Learn more: https://developers.google.com/earth-engine/landsat_c1_to_c2

  warnings.warn(warning, category=DeprecationWarning)
Number of images available between 1984-01-01 and 2024-04-04:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
     L9: 36 images
     L8: 274 images
     L7: 474 images
     L5: 106 images
Attempt 1/3 failed with error: EEException

```
