### ISSUE TITLE
Write a log file for shoreline extraction

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/coastsat_package#8]
When shorelines are extracted a log file should be generated that details what happened during the shoreline extraction process. It should detail which method was used to extract shorelines, what errors occurred during the shoreline processes, what classes were detected during the classification processes, and more. 

This file will be read by end-users so its important that can be easily read and understood by a non-technical audience. It should list which file each operation is associated it so the user understands why partial images failed.

### Tasks
- [x] List which shoreline extraction process was used (explain what it is at the top of the file)
- [x] List each filename or date+satellite the extracted shoreline is associated with
- [x] Which classes were detected
- [x] The number of sand pixels discovered
- [x]  The percentage of the image that was sand pixels

- [x] List the reason a shoreline could not be extracted from the image
   - error reading image
   - no shorelines detected within reference shoreline buffer
 
 
 ### Purpose
 The whole purpose of this feature is to make the shoreline extraction process easier to understand and debug. Hopefully, this will guide users towards modifying the correct settings.
