### ISSUE TITLE
Make preprocess_single work even if files are missing

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/coastsat_package#9]
If a file is missing in `preprocess_single` return None and just skip this file.
## Tasks
- [x] Check if each file needed to run `preprocess_single` exists or not
- [ ] If its missing return None
- [x] Maybe log why it failed - '{FILENAME} was missing from {EXPECTED_LOCATION}'

## Relevant Code
```
# fn is a list of 3 file names typically is ['ms_filename','mask_filename','pan/swir filename']
# the snippet below is from the landsat 5 code section
        fn_ms = fn[0]
        fn_mask = fn[1]
       # HERE IS WHERE IT SHOULD BE CHECKED IF ALL FILES IN FN EXIST OR NOT
        # read ms bands
        data = gdal.Open(fn_ms, gdal.GA_ReadOnly)
        # if  fn_ms doesn't exist this code will return None
        georef = np.array(data.GetGeoTransform())
```

## Exceptions Caused by this issue
```
File ~\anaconda3\envs\coastseg_transformers10\lib\site-packages\coastsat\SDS_shoreline.py:249, in extract_shorelines(metadata, settings)
    239 shoreline_date = os.path.basename(fn[0])[:19]
    241 # preprocess image (cloud mask + pansharpening/downsampling)
    242 (
    243     im_ms,
    244     georef,
    245     cloud_mask,
    246     im_extra,
    247     im_QA,
    248     im_nodata,
--> 249 ) = SDS_preprocess.preprocess_single(
    250     fn,
    251     satname,
    252     settings["cloud_mask_issue"],
    253     settings["pan_off"],
    254     collection,
    255     apply_cloud_mask,
    256 )
    257 # get image spatial reference system (epsg code) from metadata dict
    258 image_epsg = metadata[satname]["epsg"][i]

File ~\anaconda3\envs\coastseg_transformers10\lib\site-packages\coastsat\SDS_preprocess.py:462, in preprocess_single(fn, satname, cloud_mask_issue, pan_off, collection, do_cloud_mask)
    460 # read ms bands
    461 data = gdal.Open(fn_ms, gdal.GA_ReadOnly)
--> 462 georef = np.array(data.GetGeoTransform())
    463 bands = read_bands(fn_ms)
    464 im_ms = np.stack(bands, 2)

AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
```

**Comment by 2320sharon** [comment]
I modified the `preprocess_single` function to use `raise_exception_if_file_is_empty` function if any of the tif files were missing. Then I modified the loop in `extract_shorelines` to put the `preprocess_single` function into a try except block that check if the `FileNotFoundError` was raised by the  `preprocess_single` function and if it was then it logs then prints a message that one of the files was missing and continues onto the next file for shoreline extraction. The old behavior would have stopped the entire shoreline extraction process and would not have indicated which file was missing. The error message above for the old workflow clearly shows this `AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'`

```
def raise_exception_if_file_is_empty(filepath: str,msg=""):
    """
    Raises an exception if the file is empty.

    Args:
        filepath (str): The path to the file to check.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"\nFile '{filepath}' does not exist.{msg}")
```

![Image](https://github.com/user-attachments/assets/f694cba6-0a39-4ee3-bd12-ff6cb2dfb2af)

**Comment by 2320sharon** [comment]
Fixed in v0.1.75
